"""Expand password hash length

Revision ID: 559dd06933bc
Revises: 7c030bfee5b9
Create Date: 2026-07-21 14:08:06.801272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559dd06933bc'
down_revision = '7c030bfee5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
