"""Add author and thumbnail to book

Revision ID: 62c6917a0616
Revises: 559dd06933bc
Create Date: 2026-07-24 14:17:34.223963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c6917a0616'
down_revision = '559dd06933bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
